# Generated by Django 4.2 on 2023-04-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_intro_post_introduction_post_conclusion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Conclusion',
            new_name='conclusion',
        ),
    ]
