# Generated by Django 4.2 on 2023-04-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_comment_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conclusion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='introduction',
            field=models.TextField(),
        ),
    ]
