# Generated by Django 4.2 on 2023-04-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_conclusion_alter_post_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='h_body',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='h_conclusion',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='h_introduction',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
    ]
