# Generated by Django 4.2 on 2023-04-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_rename_h_body_post_body_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='conclusion_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='introduction_title',
            field=models.CharField(max_length=255),
        ),
    ]
